"""edited customer model to link user to mama mboga profile

Revision ID: 1c3341cea950
Revises: a1377facb4f6
Create Date: 2025-07-20 22:48:42.374120

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c3341cea950'
down_revision = 'a1377facb4f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint('customers_user_id_key', type_='unique')
        batch_op.drop_constraint('customers_user_id_fkey', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('customers_user_id_fkey', 'users', ['user_id'], ['id'])
        batch_op.create_unique_constraint('customers_user_id_key', ['user_id'])

    # ### end Alembic commands ###
