"""Updated models: added new column to Loans table and created a new Loan_Product model

Revision ID: 36644b3f5b70
Revises: 3ee146b31580
Create Date: 2025-07-19 12:52:19.070258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36644b3f5b70'
down_revision = '3ee146b31580'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loan_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('duration_months', sa.Float(), nullable=False),
    sa.Column('max_amount', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Enum('daily', 'weekly', 'monthly', name='repaymentfrequencies'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_product_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'loan_products', ['loan_product_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('loan_product_id')

    op.drop_table('loan_products')
    # ### end Alembic commands ###
