"""Add email field to Customer

Revision ID: 4ba5d2964fc9
Revises: e25b8ca1f68e
Create Date: 2025-07-28 11:34:03.554233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ba5d2964fc9'
down_revision = 'e25b8ca1f68e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
