"""Add is_deleted to notifications

Revision ID: 674a4b74ab9a
Revises: 7e338ccefb15
Create Date: 2025-07-23 17:28:03.744996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674a4b74ab9a'
down_revision = '7e338ccefb15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
