"""Add lender_id to customers

Revision ID: 6d3f49fc95b1
Revises: 4ba5d2964fc9
Create Date: 2025-07-28 11:41:15.525300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d3f49fc95b1'
down_revision = '4ba5d2964fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lender_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_lender_id_user',  # 👈 name it properly
            'users', 
            ['lender_id'], 
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('lender_id')

    # ### end Alembic commands ###
