"""Updated RepaymentSchedule model and changed mama_mboga role to customer

Revision ID: 92ce214b0bd4
Revises: 
Create Date: 2025-07-28 10:10:52.888178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ce214b0bd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_user_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('customers_mama_mboga_user_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['customer_user_id'])
        batch_op.drop_constraint(batch_op.f('customers_mama_mboga_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['customer_user_id'], ['id'])
        batch_op.drop_column('mama_mboga_user_id')

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('loans_borrower_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['customer_id'], ['id'])
        batch_op.drop_column('borrower_id')

    with op.batch_alter_table('repayments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(batch_op.f('repayments_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['customer_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('repayments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('repayments_user_id_fkey'), 'users', ['user_id'], ['id'])
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrower_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('loans_borrower_id_fkey'), 'users', ['borrower_id'], ['id'])
        batch_op.drop_column('customer_id')

    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mama_mboga_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('customers_mama_mboga_user_id_fkey'), 'users', ['mama_mboga_user_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('customers_mama_mboga_user_id_key'), ['mama_mboga_user_id'])
        batch_op.drop_column('customer_user_id')

    # ### end Alembic commands ###
