"""Add customers table and documents field

Revision ID: a1377facb4f6
Revises: e3071e1fd350
Create Date: 2025-07-20 22:43:50.346150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1377facb4f6'
down_revision = 'e3071e1fd350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mama_mboga_user_id', sa.Integer(), nullable=True))
        batch_op.create_unique_constraint(None, ['mama_mboga_user_id'])
        batch_op.create_foreign_key(None, 'users', ['mama_mboga_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('mama_mboga_user_id')

    # ### end Alembic commands ###
